wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
num_layers:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: random
