wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
hidden_size:
  value: 64
learning_rate:
  value: 0.001
num_layers:
  value: 5
optimizer:
  value: adagrad
weight_decay:
  value: 0
weight_init:
  value: xavier_normal
