wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
hidden_size:
  value: 64
learning_rate:
  value: 0.001
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: random
