wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.19.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1741101644
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 37
      4: 3.10.16
      5: 0.19.7
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 32
eval_freq:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
dataset:
  desc: null
  value: mnist
hidden_size:
  desc: null
  value: 64
num_layers:
  desc: null
  value: 5
optimizer:
  desc: null
  value: adagrad
weight_init:
  desc: null
  value: xavier_normal
activation:
  desc: null
  value: tanh
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
epsilon:
  desc: null
  value: 1.0e-08
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0005
wandb_project:
  desc: null
  value: Multilayer_FeedForward_Network
wandb_entity:
  desc: null
  value: jay_gupta-indian-institute-of-technology-madras
beta:
  desc: null
  value: 0.9
loss:
  desc: null
  value: cross_entropy
